### ISSUE TITLE
Preparing for inclusion in HADES

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#16]
I think Capr is a valuable resource that I would like to see added to the OHDSI HADES library. If you agree to add Capr to HADES, I would request some modifications to the repo:

- Add some unit tests (maybe not fully covering all code right now). See [CirceR](https://github.com/OHDSI/CirceR/tree/master/tests) for examples on how to implement unit tests.
- Add GitHub actions (see [description here](https://ohdsi.github.io/Hades/releaseProcess.html#Continuous_integration))
- Manually create a first release + tag
- Add a NEWS.md file (see for example [SqlRender](https://github.com/OHDSI/SqlRender/blob/master/NEWS.md))
- Add Remotes section to DESCRIPTION for CirceR, so it will automatically be installed when calling `remotes::install_github("ohdsi/Capr")`. (see example Remotes section [here](https://github.com/OHDSI/CohortMethod/blob/master/DESCRIPTION#L57)). No need to add DatabaseConnector, as it is available in CRAN.
- Make sure the master branch contains latest released version (as explained [here](https://ohdsi.github.io/Hades/releaseProcess.html)), so `remotes::install_github("ohdsi/Capr")` installs the latest released version.
- Use cosmo template for documentation website, and add a HADES link (see [here](https://github.com/OHDSI/SqlRender/blob/master/_pkgdown.yml) and [here](https://github.com/OHDSI/SqlRender/blob/master/extras/PackageMaintenance.R#L38))
- Make README.md more consistent with HADES packages (see for example [CohortMethod](https://github.com/OHDSI/CohortMethod))
  - Add badges for Github action and codecov
  - Add link to HADES
  - Modify instructions to install (no need to mention dependencies that need to be installed, but should link to HADES site for general instructions on setting up R and Java)
  - Add links to PDF versions of manual, vignettes, and a link to the Capr GitHub pages (and enable GitHub pages)

**Comment by leeevans** [comment]
Excellent news!

@schuemie please add Martin Lavallee - @mdlavallee92 - as the official owner of CAPR for OHDSI and invite him to the HADES calls. I can send you Martin's contact info if you need it.

@mdlavallee92 please respond to @schuemie regarding implementing these modifications if you're OK with being assigned this task.

**Comment by mdlavallee92** [comment]
No problem I will begin working on these updates to meet the HADES standards. Thanks @schuemie for the details on the modifications.

**Comment by leeevans** [comment]
Thanks Martin!

**Comment by schuemie** [comment]
Thanks! @mdlavallee92 is now admin of the repo. 

@leeevans : could you send me Martin's e-mail address?

**Comment by schuemie** [comment]
Just checking in: where are we on this?

**Comment by mdlavallee92** [comment]
Hi Martijn,

I pulled this over to develop waiting for @leeevans to review and then will pull to main. Sorry for the delays. 

I am having trouble with the ubuntu develop version in github actions. It says that rcmdcheck is not loaded as a package. I will review the yaml file to try to figure out what is going on.

**Comment by mdlavallee92** [comment]
Regarding the reason rcmdcheck is not loading the error message in the github actions for ubuntu develop says that {curl} can not be installed because there is a missing dependency of libcurl. Is there a way to install libcurl since it is not an R package?

**Comment by schuemie** [comment]
I've sort of given up on the develop version for GitHub Actions (see the chat in the HADES Teams channel). Feel free to delete [it](https://github.com/OHDSI/Capr/blob/develop/.github/workflows/R_CMD_check_Hades.yaml#L26) from the workflow.

**Comment by mdlavallee92** [comment]
@schuemie at long last I have finished the checklist for making this a HADES package (my apologies for the delay). Please let me know if it is missing anything. 

I am working on some additional edits to package with @ablack3 and will continuously release them as those improve. Should I release this to CRAN as well? It has no warnings or notes when I build (after I add the additional folders to .Rbuildignore).

**Comment by schuemie** [comment]
Great work! As you probably already saw, I found some further minor issues, but I'll already add Capr to HADES. 

Unfortunately, you can't release Capr to CRAN, because it depends on CirceR, which is not in CRAN (and will likely never be in CRAN because its file size is bigger than what CRAN allows).

One important thing to keep in mind: You manually created the GitHub release this time, which was necessary because it was the very first release. Next time, don't create the release manually. GitHub Actions will do that automatically once all tests have passed.

**Comment by schuemie** [comment]
Sorry, I know this is annoying, but could you rename the `main` branch to `master`? That would make it consistent with all other HADES packages (and makes the GitHub Actions, and things like the [HADES package dashboard](https://ohdsi.github.io/Hades/packageStatuses.html) work properly).

**Comment by msuchard** [comment]
I am going to push back against renaming branches.  It is now standard (and for laudable reasons) that the main branch in git repos be called `main` instead of `master`.  

So I propose the converse: HADES packages that are still using `master` should change these to `main`.

**Comment by schuemie** [comment]
That would be a massive change. Could you help me understand the benefit of spending precious develop cycles on that? To me it seems like a fairly arbitrary change.

**Comment by ablack3** [comment]
Another option - leave default branches as is.

**Comment by mdlavallee92** [comment]
I am going to close this issue as it pertains to HADES inclusion. I do think the main v master branch discussion is warranted and should be brought back up in another avenue.

**Comment by schuemie** [comment]
(We're switching all of HADES to main, so no action needs to be taken here)

Capr is now in HADES! @mdlavallee92 : would you mind posting an announcement of the current version in the [HADES announcement thread](https://forums.ohdsi.org/t/hades-development-announcements/12293/58)? For normal releases we just do a short text with the biggest changes, but for a completely new package I recommend a longer post that introduces the new package to the HADES users.
