### ISSUE TITLE
Minor documentation issues

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#27]
For a next release, it might be good to fix these:

1. The [documentation website](https://ohdsi.github.io/Capr/) still lists version 0.0.1.994 as the current version. Next time make sure to generate the website as one of the last steps (after updating the version number).
2. The [documentation website](https://ohdsi.github.io/Capr/)  is missing the GitHub link in the top right corner (see the [CohortMethod site](https://ohdsi.github.io/CohortMethod/) as example. I must admit I'm not sure why that is. The [_pkgdown.yml](https://github.com/OHDSI/Capr/blob/main/_pkgdown.yml) looks fine.
3. The vignette titles are bit ugly, like ['Capr_Attributes_Extended'](https://github.com/OHDSI/Capr/blob/main/vignettes/Capr_Attributes_Extended.Rmd#L2), instead of perhaps 'Using extended cohort attributes in Capr', which would be both human-readable and more informative.
4. The Documentation section in the [README](https://github.com/OHDSI/Capr/blob/main/README.md) doesn't list all vignettes.
5. The Installation section in the [README](https://github.com/OHDSI/Capr/blob/main/README.md) mentions a `checkCmInstallation()` function that is not part of Capr.

**Comment by schuemie** [comment]
Additionally:
6. The Github Action badge in the README currently links to `https://github.com/OHDSI/<reponame>/actions?query=workflow%3AR-CMD-check`, which is not a valid URL. I recommend replacing `<reponame>` with `Capr`.

**Comment by mdlavallee92** [comment]
Not sure why the github link is not working either. I used the template code of the other packages. I will keep looking at the files and see if I find something. 

Other issues have been addressed and the package down site has been updated (forgot to update before the release). 

This issue will close once I accept the pull request linked to these issues

**Comment by schuemie** [comment]
I found the issue with the missing GitHub link: the link to the GitHub site must be in the DESCRIPTION file. I took the liberty of pushing this fix to the develop branch.

Next time please remember to call [`fixHadesLogo`](https://github.com/OHDSI/Capr/blob/main/extras/PackageMaintenance.R#L63) after regenerating the website.
