### ISSUE TITLE
Replace deprecated `oracleTempSchema` with `tempEmulationSchema`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#28]
Several functions like ['getConceptCodeDetails()'](https://ohdsi.github.io/Capr/reference/getConceptCodeDetails.html) have an `oracleTempSchema` argument. First of all, please make sure this is really necessary. Are these functions using temp tables? Second, `oracleTempSchema` has been deprecated across HADES. Please use `tempEmulationSchema' instead, and set the default value like [this](https://github.com/OHDSI/SqlRender/blob/master/R/RenderSql.R#L140).

**Comment by mdlavallee92** [comment]
At first, I did a replace of all oracleTempSchema but good point this probably doesn't need a temp schema since it is just querying off the vocabulary schema into an R data.frame.  I will remove that option from the function. 

Issue will close when I merge the pull request.
