### ISSUE TITLE
createOccurrenceStartDateAttribute does not write Extent into JSON

### ISSUE THREAD

**Issue by Apgaj** [OHDSI/Capr#40]
Hi,
It seems that when using the Op="bt" in createOcurrenceStartDateAttribute, the Extent parameter is not actually used in JSON, which causes errors.

dx_id_Query <- createConditionOccurrence(conceptSetExpression = dx_code_omop, 
attributeList = list(createOccurrenceStartDateAttribute(Op = "bt", 
Value = "2020-01-01",
Extent = "2020-12-31")))

Ocurrence start date in JSON:
\n\"OccurrenceStartDate\": {
\n \"Value\": \"2020-01-01\",
\n\"Op\": \"bt\" 
\n}

**Comment by mdlavallee92** [comment]
Sorry for the delayed response. Thanks for your issue @Apgaj . I am updating to Caprv2 with upgrades to the UI. Your issue will no longer be valid in the new release. Please try out new Capr (available in the develop branch as a pre-release). Please let me know issues like this arise in the new version 😄
