### ISSUE TITLE
Error when multiple CSE are used in `createPrimaryCriteria` 

### ISSUE THREAD

**Issue by hms1** [OHDSI/Capr#41]
For example when trying to include a `createConditionSourceConceptAttribute` in a `PrimaryCriteria`:

```
library(Eunomia)
library(Capr)

connectionDetails <- getEunomiaConnectionDetails()
connection <- connect(connectionDetails)

index_codeset <- getConceptIdDetails(conceptIds = 0, connection = connection, vocabularyDatabaseSchema = vocabularyDatabaseSchema, mapToStandard = F)  %>%
  createConceptSetExpression(Name = "Index Event", includeDescendants = F)

source_codeset <- getConceptIdDetails(conceptIds = 0, connection = connection, vocabularyDatabaseSchema = vocabularyDatabaseSchema, mapToStandard = F)  %>%
  createConceptSetExpression(Name = "Source Event", includeDescendants = F)

attribute_list <- list()

attribute_list[[1]] <- createSourceConceptAttribute("ConditionOccurrence", source_codeset)

index_event <-  createConditionOccurrence(conceptSetExpression = index_codeset, attributeList = attribute_list)

primary <- createPrimaryCriteria(Name = "Primary Criteria", ComponentList = list(index_event), ObservationWindow = createObservationWindow(0L,0L), Limit = "fist")

cd <- createCohortDefinition(Name = "My cohort", Description = "My cohoft", PrimaryCriteria = primary)

compileCohortDefinition(cd)
```

`
Error in names(att) <- x@Name : 
  'names' attribute [1] must be the same length as the vector [0]
`

I did some digging and this is because only the first concept set is recognised during `createPrimaryCriteria`, see [here](https://github.com/OHDSI/Capr/blob/caprUpdates/R/UserCreateFn.R#L556). 

A quick fix can be implemented [here](https://github.com/hms1/Capr/blob/unnests-expressions/R/UserCreateFn.R#L563) but it might be worth considering the same issue will manifest elsewhere.

Happy to do this and make a PR if you believe it is suitable solution.

PS. Many thanks for the work on this package, it is really cool. I am starting to utilise it a fair but and would be happy to contribute other things that come up.

**Comment by mdlavallee92** [comment]
Sorry for the delayed response. Thanks for your issue @hms1. I am updating to Caprv2 with upgrades to the UI. Your issue wont be valid in the new release. Please try out new Capr (available in the develop branch as a pre-release). Please let me know issues like this arise in the new version
