### ISSUE TITLE
Inconsistent use of capitalization

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#42]
For example, `createCohortDefinition()` has capitalized argument names, such as `Name` and `PrimaryCriteria`, while `createDrugExposure()` has non-capitalized argument names such as `conceptSetExpression` and `attributeList`. `createGroup()` even mixes the two.

For consistency with the [HADES style guide](https://ohdsi.github.io/Hades/codeStyle.html) I recommend using lowercase first letters for all arguments.

**Comment by ablack3** [comment]
Sounds good @schuemie. Thanks for the feedback. We are working on a pretty major rewrite of Capr for v2 which we (@mdlavallee92 or I will present to the Hades group for feedback once we have a good implementation. We're working on the v2 branch [here](https://github.com/OdyOSG/Capr/tree/v2). The code is a bit of a mess right now though.
