### ISSUE TITLE
Passing Database Connections through functions

### ISSUE THREAD

**Issue by mdlavallee92** [OHDSI/Capr#5]
Functions accessing the OMOP Vocabulary need a database connection parameter (i.e. lookup functions). Test and update to OHDSI standard

**Comment by gowthamrao** [comment]
Either take a connection or connection details object . example
https://github.com/OHDSI/CohortDiagnostics/blob/master/man-roxygen/Connection.R
https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R#L91-L92

**Comment by gowthamrao** [comment]
Note: databaseSchema has replaced the use of schema in database connector, and a function may ask for databaseSchema in addition to connection (i.e. database+schema where the vocabulary is)
https://github.com/OHDSI/CohortDiagnostics/blob/master/R/RunDiagnostics.R#L95

**Comment by mdlavallee92** [comment]
This has been updated on the latest commit. Issue closed. Functions below:

`getConceptIdDetails(conceptsIds, connectionDetails, connection, vocabularyDatabaseSchema, oracleTempSchema, mapToStandard, simplifyToDatafreme = TRUE)`

`getConceptCodeDetails(conceptsCode, vocabulary, connectionDetails, connection, vocabularyDatabaseSchema, oracleTempSchema, mapToStandard, simplifyToDatafreme = TRUE)`

`lookupKeyword(keyword, searchType, connectionDetails, connection, vocabularyDatabaseSchema, oracleTempSchema, simplifyToDatafreme = FALSE)`
