### ISSUE TITLE
Show concept details in concept set when available

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#56]
To make sure I have the right concepts in my concept set expression, I'd like to see the concept names. Of course, at the start this information is not available: 
```r
sitagliptin <- cs(
  descendants(1580747),
  name = "Sitagliptin"
)
sitagliptin 
# conceptId includeDescendants isExcluded includeMapped
# <int> <lgl>              <lgl>      <lgl>        
#   1   1580747 TRUE               FALSE      FALSE 
```
However, I would have expected to see the information after calling `getConceptSetDetails()`:
```r
sitagliptin <- getConceptSetDetails(sitagliptin, connection, cdmDatabaseSchema)
sitagliptin 
# conceptId includeDescendants isExcluded includeMapped
# <int> <lgl>              <lgl>      <lgl>        
#   1   1580747 TRUE               FALSE      FALSE 
```
The information is there, in the internal structure of the object. Could the concept name (and other concept information) be shown when available?

**Comment by mdlavallee92** [comment]
Thanks @schuemie! 

@ablack3 can you help add this into the print statement?

The print should match the csv export from Atlas for consistency across the stack. Example below. If there is no info we can either fill it out with NAs or remove those columns. 

![image](https://user-images.githubusercontent.com/44976592/228615979-dc3e2702-3c48-4077-8895-d18ffa4a47ea.png)

**Comment by schuemie** [comment]
In ATLAS you get to see conceptId, conceptCode, conceptName, domain, standardConcept, and the 3 flags. I rather like that, but I don't feel very strongly about it.
