### ISSUE TITLE
Object inheritance

### ISSUE THREAD

**Issue by mvankessel-EMC** [OHDSI/Capr#63]
First of all I'd like to state that I'm not too familiar with S4 classes, but I am comfortable with R6.

Looking at the code, the `show` methods of the following objects are identical:
1. [opAttributeNumeric](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L19-L32),
2. [opAttributeInteger](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L55-L67),
3. [opAttributeDate](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L90-L102).

Could they inherit from an `opAttributeSuper` class, which implements this method, and any other identical methods?

If similar implementations exist elsewhere in the package I think this would significantly change code duplicity.

**Comment by mdlavallee92** [comment]
Hi @mvankessel-EMC thanks for your issue!

Yes this is probably the direction the package should go, I agree. The main focus of the v2.0.x was to overhaul the UI and ensure that the coercion from R to json worked correctly so people could create and generate cohorts. Focusing on that milestone we left decisions like this that you mention as "room for improvement" while we gauge how users engage with the package. We plan to do a v2.1.x release over the summer that works on print statements and fine-tunning the S4 classes. Your suggestion is something we will keep in mind for when we start to role that out. 

That being said, feel free to start a PR to add this enhancement into Capr. We would definitely appreciate it! Ow we will get back to it in the summer 😎

**Comment by mvankessel-EMC** [comment]
> First of all I'd like to state that I'm not too familiar with S4 classes, but I am comfortable with R6.
> 
> Looking at the code, the `show` methods of the following objects are identical:
> 
> 1. [opAttributeNumeric](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L19-L32),
> 2. [opAttributeInteger](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L55-L67),
> 3. [opAttributeDate](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L90-L102).
> 
> Could they inherit from an `opAttributeSuper` class, which implements this method, and any other identical methods?
> 
> If similar implementations exist elsewhere in the package I think this would significantly change code duplicity.

These changes are pushed into Pull Request: #64:
> Pull Request for issue: #63
> 
> opAttribute,- Numeric, Integer and Date now inherit from opAttributeSuper, which contains the `show` and `as.list` methods. `methods::is()` checks have been mildly altered, to accommodate this change.

`devtools::check()` is passing [here](https://github.com/mvankessel-EMC/Capr/actions/runs/4687177902). For commit: df23952d20e36e8424b9fcc0da531d2251c0ce96

**Comment by mdlavallee92** [comment]
closed by 2.0.3 release
