### ISSUE TITLE
procedure() not working

### ISSUE THREAD

**Issue by sutsabs** [OHDSI/Capr#70]
procedure() function is not able to take procedure conceptset to generate the query. It looks like procedure is not a valid domain.

>procedure(c4)
Error in validityMethod(object) : 
  object@domain %in% validDomains is not TRUE

**Comment by sutsabs** [comment]
<html>
<body>


> c4 ── <Capr Concept Set> [BROAD] Urethral or bladder bulking procedure_urology_(1/2)_Proc_US_FINAL ────────────────────────────────────────── # A tibble: 5 × 9   conceptId conceptCode     conceptName                  domainId vocabularyId standardConcept includeDescendants isExcluded includeMapped       <int> <chr>           <chr>                        <chr>    <chr>        <chr>           <lgl>              <lgl>      <lgl>         1   2109735 51715           Endoscopic injection of imp… Procedu… CPT4         S               TRUE               FALSE      FALSE         2  44811553 913311000000100 Injection of bulking agent … Procedu… SNOMED       S               TRUE               FALSE      FALSE         3  44806646 813391000000100 Submucosal injection of pol… Procedu… SNOMED       S               TRUE               FALSE      FALSE         4  44806647 813401000000102 Submucosal injection of pol… Procedu… SNOMED       S               TRUE               FALSE      FALSE         5  44806767 813591000000105 Transurethral subtrigonal i… Procedu… SNOMED       S               TRUE               FALSE      FALSE         > procedure(c4) Error in validityMethod(object) :    object@domain %in% validDomains is not TRUE
--
 
> | >
>


</body>
</html>

**Comment by mdlavallee92** [comment]
Thanks for your issue @sutsabs. Can you provide a bit more background to the code. How was the c4 object created in particular?

**Comment by sutsabs** [comment]
c4 object is Capr ConceptSet object with procedure concept ids.

https://www.loom.com/i/ebf9d08aeedd4440ae76298dbd7b525f

**Comment by mdlavallee92** [comment]
Thanks @sutsabs. Fixed the bug, missed the procedure occurrence domain. 

Will do the hot fix and update the version. Let me know if you find anything else
