### ISSUE TITLE
Typos using "-" instead of "-" in some documentation

### ISSUE THREAD

**Issue by pa-nathaniel** [OHDSI/Capr#75]
Spotted a couple of places in code examples where the `=` operator was mistakenly typed as `-`

See

https://github.com/OHDSI/Capr/blob/fa03ba051993380a3c69a3b5a6c23273a2cdc390/vignettes/capr_objects.Rmd#L127

and

https://github.com/OHDSI/Capr/blob/fa03ba051993380a3c69a3b5a6c23273a2cdc390/vignettes/capr_objects.Rmd#L141

looks like `eval = FALSE` on both of these chunks which is likely why it wasn't caught.

**Comment by ablack3** [comment]
Thanks for reporting this! Fixed in the develop branch.
