### ISSUE TITLE
Is there Capr support for Health Economics Data Tables

### ISSUE THREAD

**Issue by pa-nathaniel** [OHDSI/Capr#76]
I am interested in creating cohorts with inclusion definitions that rely on health economics data tables such as PAYER_PLAN_PERIOD (https://ohdsi.github.io/CommonDataModel/cdm54.html#Health_Economics_Data_Tables)

When I look at the domains supported by Capr listed in https://ohdsi.github.io/Capr/articles/capr_objects.html#definition, I only see support for clinical data tables and none for Health Economics.

Is there Capr support for building cohorts  leveraging Health Economics Data tables?

* If yes, what functionality should be used?
* If no, can you help me understand why and what would be needed to support them?

**Comment by ablack3** [comment]
Hi @pa-nathaniel, good question.

Capr's domain support exactly matches what is available in Atlas and Circe so you should be able to use the following attributes. But this has not been implemented in Capr yet. Shouldn't be too hard to add but it might still be a while before we get it done. We can add it in the next release though.

<img width="1398" alt="image" src="https://github.com/OHDSI/Capr/assets/10227522/1ad54fd2-9c28-4fe7-9b76-5706e0e62841">

**Comment by pa-nathaniel** [comment]
Got it, thanks for the info @ablack3!

I'm curious if I wanted to try creating a PR to add this, what would the steps look like? 

Is there another merged PR that adds similar functionality that could be used as a reference?

You mentioned Atlas and Circe, just to clarify would this also require an update to Circe (I think 'no' but just want to clarify)

**Comment by pa-nathaniel** [comment]
Awesome makes sense. Thanks very much for the detailed developer instructions.

And just let me say again *awesome* package!!! The more I use it the more I love it.
