### ISSUE TITLE
Possible bug in Example vignette code for applying inclusion criteria

### ISSUE THREAD

**Issue by pa-nathaniel** [OHDSI/Capr#80]
We (https://github.com/nimirea) and I suspect that the examples in https://github.com/OHDSI/Capr/blob/main/vignettes/Examples.Rmd may be out of date with the latest version of the package (2.0.5).

Namely, when we executed the example code on a CDM, we found that without wrapping the arguments to `attrition()` with `withAll()` calls, the attrition information was not properly applied in the generated cohort. 

For example, in the following lines, we suspect the lines need to be wrapped with `withAll()` for the inclusion criteria to be correctly applied.

https://github.com/OHDSI/Capr/blob/fa03ba051993380a3c69a3b5a6c23273a2cdc390/vignettes/Examples.Rmd#L56-L59

I'm curious if the developers agree these examples are out of sync with the latest version or not. Maybe we're missing something else.

I can include the actual JSON comparison if it's helpful.

**Comment by mdlavallee92** [comment]
Yes that is out dated...will correct in next release. Apologies

**Comment by pa-nathaniel** [comment]
All good! Glad it will be corrected, thank you!
