### ISSUE TITLE
Example (or tips) for using age() in defining a cohort within atttrition()?

### ISSUE THREAD

**Issue by pa-nathaniel** [OHDSI/Capr#81]
I'm interested in applying inclusion criteria "is at least 18 at index"

I bet I want to leverage the `age()` function (https://github.com/OHDSI/Capr/blob/fa03ba051993380a3c69a3b5a6c23273a2cdc390/R/attributes-op.R#L328-L343), but I'm struggling a bit to figure out how to use it in an example

I looked at the examples in https://ohdsi.github.io/Capr/articles/Examples.html but didn't find one. Also couldn't seem to find one anywhere else in the repo.

Any tips? Thanks!!

**Comment by pa-nathaniel** [comment]
I just found some relevant documentation in https://ohdsi.github.io/Capr/articles/capr_objects.html, I'll keep learning and post an answer if I can solve it!

**Comment by mdlavallee92** [comment]
@pa-nathaniel thanks for your question. you have indeed found a bug. If you want to observe the attrition based on age you can add the age as a demographic criteria to a group. This is what happens in ATLAS. I need to add a container that holds the demographic criteria to apply it to the group. A group must take in a criteria class. Code would look as such:

``` r
library(Capr)
  
  t1dConceptSet <- cs(descendants(195771), name = "T1D") 
  
  cd <- cohort(
    entry = entry(
      t1dConceptSet,
      observationWindow = continuousObservation(priorDays = 365L),
      primaryCriteriaLimit = "All"
    ),
    attrition = attrition(
      'atLeast18' = withAll(
        demographic(age(gte(18L))) # function to add
      )
    )
  )
```

**Comment by pa-nathaniel** [comment]
Ah interesting, I thought I had solved it yesterday evening by doing something like the code below.  Would this not do it?

```
library(Capr)
 
 t1dConceptSet <- cs(descendants(195771), name = "T1D") 
  
 cd <- cohort(
    entry = entry(
      t1dConceptSet,
      observationWindow = continuousObservation(priorDays = 365L),
      primaryCriteriaLimit = "All"
    ),
    attrition = attrition(
     "At least 18 at entry" = withAll(
      atLeast(
        1,
        conditionOccurrence(
          t1dConceptSet,
          age(gte(18)), firstOccurrence()
        )
      )
  )

```

**Comment by mdlavallee92** [comment]
If you are using age as an attribute to a condition this is indeed correct. However, circe allows you to use a demographic attribute as a point of attrition. This is not covered in `Capr` v2 and needs to be added.

**Comment by pa-nathaniel** [comment]
Ah great glad I wasn't too far off, thanks!
