### ISSUE TITLE
How do I specify a date range?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#89]
I'd like to specify a date range for my entry event, but I can't figure out how to do that in Capr. Here's the logic I need,  in Circe:
![image](https://github.com/OHDSI/Capr/assets/6713328/27767a7d-7442-4eac-abd1-ffcc7e6303ef)

This is what I was able to do so far:

```r
h1n1pdmVaccines <- cs(
  descendants(c(40166130, 40166144, 40166607, 40166608, 40166609, 40166611, 40213187, 40225009, 40240135, 42902936, 45776785)),
  name = "H1N1pdm vaccines"
)

h1n1pdmVaccinesCohort <- cohort(
  entry = entry(
    drugExposure(h1n1pdmVaccines, firstOccurrence())
  )
)
```

I think the [list of examples](https://ohdsi.github.io/Capr/articles/Examples.html) is really helpful. Maybe it could be expanded a bit to cover this?

**Comment by schuemie** [comment]
Awesome. Thanks!

**Comment by rbcavanaugh** [comment]
Hi - This was also a helpful example for me, but I'm not able to implement it: 

```
# copied from above
h1n1pdmVaccines <- cs(
  descendants(c(40166130, 40166144, 40166607, 40166608, 40166609, 40166611, 40213187, 40225009, 40240135, 42902936, 45776785)),
  name = "H1N1pdm vaccines"
)

h1n1pdmVaccinesCohort <- cohort(
  entry = entry(
    drugExposure(h1n1pdmVaccines, 
                           firstOccurrence(), #first occurrence attribute
                            startDate(bt('2009-09-01', '2010-05-31') # occurrence start date attribute
  )
)
```

```
Error in (function (classes, fdef, mtable) :
    unable to find an inherited method for function 'bt' for signature '"character"'
```

wrapping the dates in `as.Date()` appears to resolve the error but I'm not sure if that generates the correct query. thanks!

**Comment by mdlavallee92** [comment]
hey @rbcavanaugh adding as.Date is correct. Not sure what I was thinking in the example 😅 


Should be.....

```r
h1n1pdmVaccinesCohort <- cohort(
  entry = entry(
    drugExposure(h1n1pdmVaccines, 
                           firstOccurrence(), #first occurrence attribute
                            startDate(
                                 bt(as.Date('2009-09-01'), as.Date('2010-05-31')) # occurrence start date attribute
                             )
                           )
                          )
       )

```

the [bt](https://github.com/OHDSI/Capr/blob/main/R/attributes-op.R#L264-L288) (any of the op's for that fact) operator works either as an int, numeric or Date so you need to add the coercion to the syntax. Probably a good habit because it verifies what type the structure is. 

Make sense? But let me know if you think this should be amended further within the function

**Comment by mdlavallee92** [comment]
^also it will work.....to check if the cohort from Capr worked properly you can always run the commands...

```r
jj <- compile(h1n1pdmeVaccinesCohort, pretty = TRUE) #pretty is a call to jsonlite
sql <- CirceR::buildCohortQuery(jj, options = CirceR::createGenerateOptions(generateStats = FALSE))
```

If the sql build it means the json is proper CIRCE.

**Comment by rbcavanaugh** [comment]
great thanks! Much appreciated - the package is really promising for our preferred workflow - slowly learning how to map the ATLAS options to the Capr functions.
