### ISSUE TITLE
Allow numeric as `offsetDays`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Capr#90]
Currently this throws an error:
```r
fixedExit(offsetDays = 0)
# Error in validObject(.Object) : 
#   invalid class “FixedDurationExit” object: invalid object for slot "offsetDays" in class "FixedDurationExit": got class # "numeric", should be or extend class "integer"
```

which technically is correct, but would be nice if `numeric` is also allowed since R defaults all numbers to numeric.

**Comment by mdlavallee92** [comment]
adding a coercion to integer within the function. in the json serialization if the value is numeric I have seen it turn into a double so I force everything to be an integer to avoid that problem. Adding the fix in the develop branch for now and will push to main when I add a few updates to the vignettes. Will close this issue when it is merged into main

**Comment by mdlavallee92** [comment]
See adjustment [here](https://github.com/OHDSI/Capr/blob/develop/R/exit.R#L153)
