### ISSUE TITLE
Add typeConceptIds as attributes to all domain criteria

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Capr#93]
Add typeConceptIds as attributes to all domain criteria. We often need to delineate between claims, EHR, NLP in CDMs with multiple data provenances. 

Can we add typeConceptId support?

**Comment by mdlavallee92** [comment]
add drug, condtion, measurement, observation, procedure and visit type concept as an attribute. You will use it this way:

``` r
t2d <- cs(descendants(201826), name = "T2D")

claim_type <- conditionType(
  ids = c(32810), # claim type concept
  connection = connection,
  vocabularyDatabaseSchema = "vocab"
)

cd <- cohort(
  entry = entry(
    conditionOccurrence(conceptSet = t2d, claim_type),
    observationWindow = continuousObservation(priorDays = 365L),
    primaryCriteriaLimit = "First"
  ),
  attrition = attrition(
    expressionLimit = "All"
  ),
  exit = exit(
    endStrategy = observationExit()
  ),
  era = era(eraDays = 7L)
)


ll <- compile(cd, pretty = TRUE)
cat(ll)
```

**Comment by alondhe** [comment]
Just curious if the connection is truly needed; if we bring the full list of type concept ids, does Circe truly require the rest of the metadata to be there? And each has a different class (ConditionType, DrugType) -- are there differences inherent between these?

It is working though, so many thanks for the quick add!

**Comment by mdlavallee92** [comment]
this is tricky....no the connection is not totally needed if you have the concept id. That is more for completion sake. May need to add helpers for this
