### ISSUE TITLE
Error when calling cs function

### ISSUE THREAD

**Issue by haydenbspence** [OHDSI/Capr#96]
System:  Broadsea 3.5

I run the following vignette

```
library(DatabaseConnector)
library(Capr)

cs0 <- cs(descendants(443238, 201820, 442793),
          descendants(exclude(195771, 201254, 435216, 761051, 4058243, 40484648)),
          name = "Type 2 diabetes mellitus (diabetes mellitus excluding T1DM and secondary)")
ch <- cohort(
  entry = entry(
    conditionOccurrence(cs0),
    observationWindow = continuousObservation(priorDays = 365)
  ),
  exit = exit(
    endStrategy = observationExit()
  )
)
```

Error:
```
> cs0 <- cs(descendants(443238, 201820, 442793),
+           descendants(exclude(195771, 201254, 435216, 761051, 4058243, 40484648)),
+           name .... [TRUNCATED] 
Error in cs(descendants(443238, 201820, 442793), descendants(exclude(195771,  : 
  could not find function "cs"
```

**Comment by mdlavallee92** [comment]
what version of Capr are you using? Working in my local on v2.0.8. Could Broadsea be on an old version?

**Comment by haydenbspence** [comment]
> what version of Capr are you using? Working in my local on v2.0.8. Could Broadsea be on an old version? 

Just looked into the image for [broadsea-hades](https://hub.docker.com/r/ohdsi/broadsea-hades/tags), and it's a 2yrs old. 

I updated using the HADES wide release and Capr is working fine now. 

This seems to be an issue with Broadsea not being aligned with the most recent HADES wide release, not Capr. 

Related issue:
https://github.com/OHDSI/Hades/issues/37
